version: '2'
services:
  web:
    build: .
    command: npm start # node app.js
    ports:
      - "8000:8000"
    volumes:
      - ./code:/usr/src/code
    depends_on:
      - db
    links:
      - db
    environment:
      - PORT=8000
      - DB_PORT=mongodb://db:27017
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
